<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Ledger of credits generated by returns (return_type = 'deposit')
        Schema::create('supplier_credits', function (Blueprint $table) {
            $table->id();

            $table->foreignId('supplier_id')
                ->constrained('suppliers')
                ->cascadeOnDelete();

            $table->foreignId('purchase_return_id')
                ->unique() // 1 return -> 1 credit
                ->constrained('purchase_returns')
                ->cascadeOnDelete();

            $table->decimal('amount', 15, 2);            // credit created
            $table->decimal('remaining_amount', 15, 2);  // amount left to apply
            $table->string('status')->default('open');   // open|closed
            $table->timestamps();

            $table->index(['supplier_id', 'status']);
        });

        // Applications of credits to purchase payments later on
        Schema::create('purchase_payment_credit_applications', function (Blueprint $table) {
            $table->id();

            // existing purchase payments table in your schema
            $table->foreignId('purchase_payment_id')
                ->constrained('purchase_payments')
                ->cascadeOnDelete();

            $table->foreignId('supplier_credit_id')
                ->constrained('supplier_credits')
                ->cascadeOnDelete();

            $table->decimal('amount', 15, 2);
            $table->timestamps();

            $table->unique(['purchase_payment_id', 'supplier_credit_id'], 'uniq_purchase_payment_credit');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('purchase_payment_credit_applications');
        Schema::dropIfExists('supplier_credits');
    }
};
