version: '3.8'
services:
  soketi:
    image: quay.io/soketi/soketi:1.0-16-alpine
    environment:
      - SOKETI_DEFAULT_APP_ID=local-app
      - SOKETI_DEFAULT_APP_KEY=local-key
      - SOKETI_DEFAULT_APP_SECRET=local-secret
      - SOKETI_HOST=0.0.0.0
      - SOKETI_PORT=6001
    ports:
      - "6001:6001"
